# Generated by Django 5.1.3 on 2024-11-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="time_limit",
            field=models.PositiveIntegerField(default=86400),
        ),
    ]
